"""empty message

Revision ID: 14f67f2e905
Revises: 4848557bc00
Create Date: 2015-11-04 23:34:26.601677

"""

# revision identifiers, used by Alembic.
revision = '14f67f2e905'
down_revision = '4848557bc00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaitem', sa.Column('file_size', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaitem', 'file_size')
    ### end Alembic commands ###
