"""initial

Revision ID: 4848557bc00
Revises: None
Create Date: 2015-11-02 22:09:10.469914

"""

# revision identifiers, used by Alembic.
revision = '4848557bc00'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediaitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('origin_date', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('media_type_cd', sa.Integer(), nullable=False),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('status_cd', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['mediaitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediastore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('designator', sa.String(length=55), nullable=False),
    sa.Column('base_dir', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designator')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediaitem_mediastore',
    sa.Column('mediaitem_id', sa.Integer(), nullable=False),
    sa.Column('mediastore_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['mediaitem_id'], ['mediaitem.id'], ),
    sa.ForeignKeyConstraint(['mediastore_id'], ['mediastore.id'], ),
    sa.PrimaryKeyConstraint('mediaitem_id', 'mediastore_id')
    )
    op.create_table('mediaitem_tag',
    sa.Column('mediaitem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mediaitem_id'], ['mediaitem.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('mediaitem_id', 'tag_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mediaitem_tag')
    op.drop_table('mediaitem_mediastore')
    op.drop_table('tag')
    op.drop_table('mediastore')
    op.drop_table('mediaitem')
    ### end Alembic commands ###
