"""empty message

Revision ID: 51de9e1698b
Revises: 14f67f2e905
Create Date: 2015-11-05 23:17:43.911210

"""

# revision identifiers, used by Alembic.
revision = '51de9e1698b'
down_revision = '14f67f2e905'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaitem', sa.Column('hash_cd', sa.String(length=32), nullable=True))
    op.add_column('mediaitem_mediastore', sa.Column('designation_cd', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaitem_mediastore', 'designation_cd')
    op.drop_column('mediaitem', 'hash_cd')
    ### end Alembic commands ###
